### ISSUE TITLE
Offset field should accept negative integer - assembler

### ISSUE THREAD

**Issue by PutawanDE** [RiwEZ/261304-AssemblySim#9]
### Breaking testcase
```
lw 0 0 -1
```
### Output
```
Traceback (most recent call last):
  File "D:\PUTAWAN\ComputerProjects\ComArch\261304-AssemblySim\assembler.py", line 25, in <module>
    main()
  File "D:\PUTAWAN\ComputerProjects\ComArch\261304-AssemblySim\assembler.py", line 20, in main
    for item in p.execute():
  File "D:\PUTAWAN\ComputerProjects\ComArch\261304-AssemblySim\assembler\asm_parser.py", line 41, in execute
    res[i] = node.evaluate(self.var_map)
  File "D:\PUTAWAN\ComputerProjects\ComArch\261304-AssemblySim\assembler\asm_ast.py", line 61, in evaluate
    if type(self.var) != int: raise Exception('I_ins immediate is not int')
Exception: I_ins immediate is not int
```
### Expected output:
should pass, no exception
```
8454143
```

**Comment by PutawanDE** [comment]
fixed with 5f38d923f1dbd225a07df5c04870c409065f6c7e
